# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gamestools',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/gamestools',
                'lib_path': 'gamestools'},
  'syms': { 'gamestools.turnbased': { 'gamestools.turnbased.TurnBasedGame': ('turnbased.html#turnbasedgame', 'gamestools/turnbased.py'),
                                      'gamestools.turnbased.TurnBasedGame.__init__': ('turnbased.html#__init__', 'gamestools/turnbased.py'),
                                      'gamestools.turnbased.TurnBasedGame.__repr__': ('turnbased.html#__repr__', 'gamestools/turnbased.py'),
                                      'gamestools.turnbased.TurnBasedGame._change_player': ( 'turnbased.html#_change_player',
                                                                                             'gamestools/turnbased.py')}}}