# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gamestools',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/gamestools',
                'lib_path': 'gamestools'},
  'syms': { 'gamestools.turnbased': { 'gamestools.turnbased.TurnBasedGame': ( 'https://Jorgvt.github.io/turnbased.html#turnbasedgame',
                                                                              'https://github.com/Jorgvt/gamestools/blob/master/gamestools/turnbased.py#L11'),
                                      'gamestools.turnbased.TurnBasedGame.__init__': ( 'https://Jorgvt.github.io/turnbased.html#__init__',
                                                                                       'https://github.com/Jorgvt/gamestools/blob/master/gamestools/turnbased.py#L17'),
                                      'gamestools.turnbased.TurnBasedGame.__repr__': ( 'https://Jorgvt.github.io/turnbased.html#__repr__',
                                                                                       'https://github.com/Jorgvt/gamestools/blob/master/gamestools/turnbased.py#L24'),
                                      'gamestools.turnbased.TurnBasedGame._change_player': ( 'https://Jorgvt.github.io/turnbased.html#_change_player',
                                                                                             'https://github.com/Jorgvt/gamestools/blob/master/gamestools/turnbased.py#L38')}}}